default: hello

hello: hello.c
	gcc hello.c -o hello.exe -std=c18 -Wall -pedantic

example: L01_Example.c
	gcc L01_Example.c -o example.exe -std=c18 -Wall -pedantic	
	
clean: 
	rm -f hello.exe
	rm -f example.exe

